# Generated by Django 4.2.4 on 2023-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_page', '0002_remove_imageblog_date_posted_imageblog_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='imageblog',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
