# Generated by Django 4.2.4 on 2023-09-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_page', '0003_categories_imageblog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
